language: node_js
node_js:
- 8.10.0
before_install:
- mkdir openssl/ca/private
- openssl aes-256-cbc -k "$super_secret_password" -in cakey.pem.enc -out openssl/ca/private/cakey.pem
  -d
- ls -l openssl/ca/private
install:
- npm install mocha
- npm install -g istanbul
- npm install -g codecov
script:
- codecov
env:
  global:
    secure: s/3Gq2FkP4b7ELBkw3cXmdBnf0YJb72Fpj2sv+O862X5ZODrIFCF/7R4DfaSX7SrkvZH/nXsawgaudCw+sqeAOJKNuqcNjnpOzJmoEjtJUlOU4AcjgFmeuvbyaKw6HhBAy2U04zUKz+r8NhG0D8h9l5s7WkdLvC5Oa0qXHm8Y/8vR+1CJ58N0CE904lHC8BGij4PlRJrb1fSaGM0wq/6T//He7d+5ld7ocFLxPa4zuCqxZIUtObRQyJsM1CKXO60jCMs9V7gGynBPqjheiXdSDT7IL2Nu1n7scapx87k59uPTcE3p3JKI6ERpWZFLrF8Yi0dPPy3QyIWwsvg0uRSWpmzznRE/hgTSkozuB/chidEfMZRmg4sUOFXZzx5P0T23DrUddV6jrls1jFgtRTmYmqcUcoGEP1MAO4feJQ743FEGYvKXzSxk1TZoJy7hpEBXjBNQFvuJYQkvhxU5Od/sBwVV4n67e6R5U2CVOnv5wg9HH4YnRkj2Y+4fwTGEnjpdivUJSawklHS5UdlLWfdlqT4MtMBYZTiRwtorGNRWQHhWHmKIoThO8k/3ObcxwBJNoGFz0qeH2DPa3HaBJ1dwCnLu1enA8sjyffA8o2O97XxPNrfBCs8Tyh6iQPJqHv5lSC70J5CoNP7fHA9shl+MOynI8awwWYIkFrvkkbK3C8=
deploy:
  provider: heroku
  api_key:
    secure: bL6IUw+xAdI3YeqRRLWsztJBVVtIa3Ca6SaU1qs6FD+UShxQafD8wV1aYLxX7hJQ7dPflTDUMOkatqBELeeiCIfGajUnlC5L+vYXSP9OiY3rgMV6sJN5Y3GbsTX10pjj1KuoWfNCXuQPzX5KHceU9zVecHRO0vR/hRtKBYL89RWIHHWUdFdo9kfSwG9YVOAj7SFtGiTRh5/Vzkq6ukZS48kYsR5LMMs42Ka1ctXiDnWI2c1TjeWbbTH91sv6ap8Mf9829YFUIb5XfkQFgcOUb2YoLUnTypFyB9aFrQdS1XLzHIrASivTXpSL86k+7nuuStQ9u1S2XHqBcCs+0ePrG16jW/MXDOP4rBd/dKBlKijlREZ/eoq9Hhp6pjOA9vITnAaY/TEVxSbB3eES6myteUXfeE3EIbuPkALsCbRI0DSBmCvmig9DlM3nGhJ+A2c1Xskb73kh7iL2RSXrxzoV+wYs02UcrhLptVXk/xm3npNUyo/lpyrIY/s6SL+FZUsnskZzBlDP5h1I3EDwHGkNZtBfdYZTRVJVsvICr880UanAUT6e2Jl2bAwguGIaCV3nKU4iulM8wmFV0ecylq6TQzwS49OvebJCQm8XULdIlZLJ6D/dnYNA4cj7rrW+wMWm/W4GuPiTcHFhpRgS++wNWD5LM3ZDRXYysxbgAZa3Z2s=
