language: node_js
node_js:
- 8.10.0
before_install:
- mkdir openssl/ca/private
- openssl aes-256-cbc -k "$super_secret_password" -in cakey.pem.enc -out openssl/ca/private/cakey.pem
  -d
- ls -l openssl/ca/private
install:
- npm install mocha
- npm install -g istanbul
- npm install -g codecov
script:
- codecov
env:
  global:
    secure: s/3Gq2FkP4b7ELBkw3cXmdBnf0YJb72Fpj2sv+O862X5ZODrIFCF/7R4DfaSX7SrkvZH/nXsawgaudCw+sqeAOJKNuqcNjnpOzJmoEjtJUlOU4AcjgFmeuvbyaKw6HhBAy2U04zUKz+r8NhG0D8h9l5s7WkdLvC5Oa0qXHm8Y/8vR+1CJ58N0CE904lHC8BGij4PlRJrb1fSaGM0wq/6T//He7d+5ld7ocFLxPa4zuCqxZIUtObRQyJsM1CKXO60jCMs9V7gGynBPqjheiXdSDT7IL2Nu1n7scapx87k59uPTcE3p3JKI6ERpWZFLrF8Yi0dPPy3QyIWwsvg0uRSWpmzznRE/hgTSkozuB/chidEfMZRmg4sUOFXZzx5P0T23DrUddV6jrls1jFgtRTmYmqcUcoGEP1MAO4feJQ743FEGYvKXzSxk1TZoJy7hpEBXjBNQFvuJYQkvhxU5Od/sBwVV4n67e6R5U2CVOnv5wg9HH4YnRkj2Y+4fwTGEnjpdivUJSawklHS5UdlLWfdlqT4MtMBYZTiRwtorGNRWQHhWHmKIoThO8k/3ObcxwBJNoGFz0qeH2DPa3HaBJ1dwCnLu1enA8sjyffA8o2O97XxPNrfBCs8Tyh6iQPJqHv5lSC70J5CoNP7fHA9shl+MOynI8awwWYIkFrvkkbK3C8=
deploy:
  provider: heroku
  api_key:
    secure: CCCwYnF7XvwV9D3UVvvnFv2MoGfZLZw1/EUq4/urOOVNFKiJEW7Xs0E041nH0r0zz47Ja+qX0QENmEg1YaiISGfi/z42cXlsBe1wZy5vHe+NbLLF395AqiPCtBYs+7DXXXVECOhuD46B5BnSPGs52o+Kh4KdVHGkJrjjJXyIkDZtmR9faruQA52/TF+1II3/UIRltwMn91UQhFUxbPHUu1Rw/YY4Uc2LTtbIvx+/Jo/l9ih19hwG2lW5gcQDTRz75BBX3XvqxL9dbi5kis8/J/wU01C1LB69H9qJambQNpZzjrJAzT49IMCLgNr6KoVwmyqiPRM3SwLCuBsoGwfIP7W6VLfk9sERUlfMARaqK1BMUb47NhhwWfInoWuUrNxngz2dJtDGv8XPJt4fS2P3HT3iot15EF5ajaHtPFThJ4TicGCiDt6XbQXX6AIKAWR6x78Q90K3C8zG3u1z0HVZtfbUl9IyGjyAmEHPbG+jUBLDt9JACBL2qxfOGvysDPa6eedTR8KVBG1LIl3+BZNJaTbudcDqJ0Eltwrgc8mkbTAA3Y8L/zqlODYD5JyWsTBHE9xNtQBvEm5iVMIraL64Lrj3KoUPgf4WkXh0iWIs7D8tMQNicdUfjjQBQi23P/1y39nKFJo8zArQkywqnT7lrFT6XPQ/o/vexyu3XTYNbyI=
  app: signu-ca
  run:
    - "mkdir openssl/ca/private"
    - "ls -l openssl/ca/private"
